const express     	= require('express');
const app     	 	= express();
const server        = require('http').Server(app);
const io            = require('socket.io')(server);
const port    	 	= process.env.PORT || 7777;
const mongoose 	 	= require('mongoose');
var passport 		= require('passport');
const flash    	 	= require('connect-flash');
const morgan        = require('morgan');
const cookieParser  = require('cookie-parser');
const bodyParser    = require('body-parser');
const session       = require('express-session');
const configDB 	 	= require('./config/database.js');
mongoose.connect(configDB.url);
require('./config/passport')(passport);
app.use(passport.initialize());
app.use(passport.session());
app.use(morgan('dev')); 
app.use(cookieParser()); 
app.use(bodyParser()); 
app.set('view engine','pug');
app.use(session({ secret: 'probleprobleproble' }));
app.use(flash()); 
app.use(express.static(__dirname + '/public'));
require('./app/routes.js')(app,io,passport);
server.listen(port);console.log('This is the THREEChesReactsNutt ' + port + ' with Express,Jade,React,THREE.JS & Socket.io');